### ISSUE TITLE
App stop working at every ~2 days

### ISSUE THREAD

**Issue by koralu** [bogkonstantin/android_income_sms_gateway_webhook#16] opened 2022-01-20 10:04 UTC
On an Android 7 platform at every ~two days, the app stop working (the tablet is permanently plugged in so there aren't battery issues). SMS are received by the tablet but the app doesn't forward it. Do you have any idea how to debug this behavior and how to fix it?

**Comment by bdgreenweb** [comment] 2022-02-20 09:45
Your mobile closed this app to run in background. Its a battery optimization feature offered by most handset. You can turn off it from your phone settings. Just disable battery optimization for this app and it will run in background. I have tried this and its working properly. I don't know how long it will work because few handset provider closed app if ram and cpu is low.

@bogkonstantin it will be great if you add this app inside notification bar which will prevent app from closing even when phone locked or out of memory. For example,

![83610F14-7551-42C0-918E-A996770814B6](https://user-images.githubusercontent.com/51988436/154836909-9748d5b6-5513-4325-813c-8bed4ac1176d.jpeg)
![934CD1E4-7728-406C-B0AA-0B6E2696AF50](https://user-images.githubusercontent.com/51988436/154836917-7f32ce7b-8c62-4cca-b4ac-d0628dcc0a9b.jpeg)

By the way thanks.

**Comment by SamSirry** [comment] 2022-09-02 04:07
This is caused by power saving features and settings from Android.

You must add an exception to this app to prevent it from being hibernated by the system. Different Android versions and different operating system issuer means the way to do this varies. You can start looking under the battery section in the settings.

**Closed** 2023-01-17 17:44 UTC
